version: '3.8'
services:
  backend:
    build: ./backend
    container_name: ematchef_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: ematchef_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    container_name: ematchef_db
    environment:
      POSTGRES_DB: ematchef
      POSTGRES_USER: ematchef
      POSTGRES_PASSWORD: ematchef
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: