services:
  backend:
    build:
      context: ./backend
    container_name: ematchef_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t public
    entrypoint: sh -c "composer install && php bin/console doctrine:migrations:migrate --no-interaction && php -S 0.0.0.0:8000 -t public"


  frontend:
    build:
      context: ./frontend
    container_name: ematchef_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: ematchef_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ematchef
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: